### ISSUE TITLE
IInterfacerInterface.aidl is under the GPL

### ISSUE THREAD

**Issue by Raymonf** [jereksel/LibreSubstratum#178]
This project is licensed under the MIT license, while it clearly uses a piece of code (regardless of its use or usage) that's licensed under the GPL from Substratum: https://github.com/jereksel/LibreSubstratum/blob/develop/app/src/main/aidl/projekt/substratum/IInterfacerInterface.aidl

Original file: https://github.com/substratum/substratum/blob/release/app/src/main/aidl/projekt/substratum/IInterfacerInterface.aidl

The easiest fix would be to move to GPLv3 and throw in the copyright stuff you need.

Dev fix plz ~~when add volte~~ ?

**Comment by jereksel** [comment]
API (which aidl file defines) cannot be copyrighted: https://www.publicknowledge.org/news-blog/blogs/why-you-cant-copyright-an-api
I left Subs copyright there due to respect.

**Comment by jereksel** [comment]
Issue was resolved. Thank you for bringing this up.
