### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by dimqua** [jereksel/LibreSubstratum#81]
Please consider to add the app to the F-Droid repository. 

Currently, however, LibreSubstratum [doesn't complies](https://gitlab.com/fdroid/rfp/issues/363#note_42090316) with F-Droid's inclusion policy.

**Comment by jereksel** [comment]
Thank you for suggestion.

I was thinking about adding Libre to FDroid repository, however now I'm working on version 1.0 to be released for testers and general public. The biggest issue is unfortunatelly #21. However recently I saw adb compiled without using whole AOSP repo (https://github.com/bonnyfone/adb-arm), so I hope that I could do the same with aapt.

**Comment by jereksel** [comment]
@dimqua I'll create new request on F-Droid when 1.0 will be ready.

**Comment by jereksel** [comment]
Request was opened: https://gitlab.com/fdroid/fdroiddata/merge_requests/2625

**Comment by jereksel** [comment]
LibreSubstratum was merged to Fdroid:
https://gitlab.com/fdroid/fdroiddata/commit/a36b5e674e9737edcff86b0f026089d48768d302
https://gitlab.com/fdroid/fdroiddata/commit/49f76f6753e428cbd7a743c0bd026c6953662c04
